version = 1
enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
dontCull = []
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 16
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 2.0
paintingCulling = true
leavesCullingMode = "FAST"
leavesCullingAmount = 2
includeMangroveRoots = false
endGatewayCulling = false
beaconBeamCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
azurelib = true
mekanismadditions = true
framedblocks = true
farmersdelight = true
enderio = true
supplementaries = true
apotheosis = true
itemcollectors = true
create_easy_structures = true
deeperdarker = true
endrem = true
storagedrawers = true
mekanism = true
create = true
mahoutsukai = true
minecolonies = true
projectvibrantjourneys = true
structurize = true
cataclysm = true
gtceu = true
multipiston = true
irons_spellbooks = true
minecraft = true
irons_jewelry = true
lootr = true
comforts = true
domum_ornamentum = true
createaddition = true
twilightforest = true
mekanismgenerators = true
avaritia = true
create_sa = true
bellsandwhistles = true
ae2 = true
amendments = true
apothic_enchanting = true
immersiveengineering = true
relics = true
sophisticatedbackpacks = true
torchmaster = true
mob_grinding_utils = true
